swagger: '2.0'
info:
  title: User MS
  version: "0.1"
  description: USER MS
consumes:
  - application/json
produces:
  - application/json
basePath: "/api/user"

paths:
   /registration:
    post:
      tags: [User]
      operationId: app.registration
      parameters:
          -$ref: '#/parameters/user_body'
      responses:
        200:
          description: Return status
        404:
          description: Already exists
   /getRole/{user_id}:
     get:
       tags: [User]
       operationId: app.getRole
       parameters:
         -$ref: '#/parameters/user_id'
       responses:
         200:
           description: Return user role
         404:
           description: User not found
    /getUserDetails/{user_id}:
      get:
        tags: [User]
        operationId: app.getUserDetails
        parameters:
          -$ref: '#/parameters/user_id'
        responses:
          200:
            description: Return user details
          404:
            description: User not found
     /getUserImages/{user_id}:
       get:
         tags: [User]
         operationId: app.getUserImages
           parameters:
             -$ref: '#/parameters/user_id'
         responses:
           200:
             description: Return user images
           404:
             description: User not found
      /addImageToUser:
        put:
          tags: [User]
          operationId: app.addImageToUser
            parameters:
              -$ref: '#/parameters/image_body'
          responses:
            200:
              description: Added image to user
            404:
              description: Image not added
      /changePassword:
        put:
          tags: [User]
          operationId: app.changePassword
            parameters:
              -$ref: '#/parameters/password_body'
          responses:
            200:
              description: Changed password successfully
            404:
              description: Password not changed
      /changeGender:
        put:
        tags: [User]
        operationId: app.changeGender
          parameters:
            -$ref: '#/parameters/gender_body'
        responses:
          200:
            description: Changed gender successfully
          404:
            description: Gender not changed
      /changeAge:
        put:
        tags: [User]
        operationId: app.changeAge
          parameters:
            -$ref: '#/parameters/age_body'
        responses:
          200:
            description: Changed age successfully
          404:
            description: Age not changed
      /changePhone:
        put:
          tags: [User]
          operationId: app.changePhone
            parameters:
              -$ref: '#/parameters/phone_body'
          responses:
            200:
              description: Changed phone successfully
            404:
              description: Phone not changed
      /changeCity:
        put:
          tags: [User]
          operationId: app.changeCity
            parameters:
              -$ref: '#/parameters/city_body'
          responses:
            200:
              description: Changed city successfully
            404:
              description: City not changed
      /changeCountry:
        put:
          tags: [User]
          operationId: app.changeCountry
            parameters:
              -$ref: '#/parameters/country_body'
          responses:
            200:
              description: Country changed successfully
            404:
              description: Country not changed
      /changeAddress:
        put:
          tags: [User]
          operationId: app.changeAddress
            parameters:
              -$ref: '#/parameters/address_body'
          responses:
            200:
              description: Address changed successfully
            404:
              description: Address not changed
      /changePostalCode:
        put:
          tags: [User]
          operationId: app.changePostalCode
            parameters:
              -$ref: '#/parameters/postal_body'
          responses:
            200:
              description: Postal code changed successfully
            404:
              description: Postal code not changed

parameters:
  user_body:
    name: user_body
    description: Body of a user
    in: body
    type: string
    schema:
      required:
        -username
        properties:
          username:
            type: string
          name:
            type: string
          surname:
            type: string
          email:
            type: string
          password:
            type: string
  user_id:
    name: user_id
    description: User unique id
    in: path
    type: string

  image_body:
    name: image_body
    description: Body of a image
    in: body
    type: string

  password_body:
    name: password_body
    description: Body of a password
    in: body
    type: string

  gender_body:
    name: gender_body
    description: Body of a gender
    in: body
    type: string

  age_body:
    name: age_body
    description: Body of a age
    in: body
    type: string

  phone_body:
    name: phone_body
    description: Body of a phone
    in: body
    type: string

  city_body:
    name: city_body
    description: Body of a city
    in: body
    type: string

  country_body:
    name: country_body
    description: Body of a country
    in: body
    type: string

  address_body:
    name: address_body
    description: Body of an address
    in: body
    type: string

  postal_body:
    name: postal_body
    description: Body of a postalCode
    in: body
    type: string
