swagger: '2.0'
info:
  title: User MS
  version: "0.3"
  description: USER MicroService
consumes:
  - application/json
produces:
  - application/json
basePath: "/api/user"
paths:
  /registration/:
    post:
      tags: [ User ]
      operationId: app.registration
      parameters:
        - $ref: '#/parameters/user_body'
      responses:
        200:
          description: Return status
        409:
          description: Already exists

  /role/{user_id}:
    get:
      tags: [User]
      operationId: app.getRole
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return user role
        404:
          description: User not found
  /details/{user_id}:
    get:
      tags: [User]
      operationId: app.getUserDetails
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return user details
        404:
          description: User not found
  /send-email/{user_id}:
    post:
      tags: [User]
      operationId: app.sendVerificationEmail
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return successfully sent
        404:
          description: User not found
  /verify/:
    put:
      tags: [User]
      operationId: app.verifyUser
      parameters:
        - $ref: '#/parameters/verification_body'
      responses:
        200:
          description: Return successfully verified
        400:
          description: Codes do not match
        404:
          description: User not found
  /images/{user_id}:
    get:
      tags: [Image]
      operationId: app.getUserImages
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return user images
        404:
          description: User not found
  /add-image:
    post:
      tags: [Image]
      operationId: app.addImageToUser
      parameters:
        - $ref: '#/parameters/image_body'
      responses:
        200:
          description: Added image to user
        404:
          description: Image not added
  /change-password:
    put:
      tags: [User]
      operationId: app.changePassword
      parameters:
        - $ref: '#/parameters/password_body'
      responses:
        200:
          description: Changed password successfully
        404:
          description: Password not changed
  /change-phone:
    put:
      tags: [User]
      operationId: app.changePhone
      parameters:
        - $ref: '#/parameters/phone_body'
      responses:
        200:
          description: Changed phone successfully
        404:
          description: Phone not changed
  /change-city:
    put:
      tags: [User]
      operationId: app.changeCity
      parameters:
        - $ref: '#/parameters/city_body'
      responses:
        200:
          description: Changed city successfully
        404:
          description: City not changed
  /change-country:
    put:
      tags: [User]
      operationId: app.changeCountry
      parameters:
        - $ref: '#/parameters/country_body'
      responses:
        200:
          description: Country changed successfully
        404:
          description: Country not changed
  /change-address:
    put:
      tags: [User]
      operationId: app.changeAddress
      parameters:
        - $ref: '#/parameters/address_body'
      responses:
        200:
          description: Address changed successfully
        404:
          description: Address not changed
  /change-postal:
    put:
      tags: [User]
      operationId: app.changePostalCode
      parameters:
        - $ref: '#/parameters/postal_body'
      responses:
        200:
          description: Postal code changed successfully
        404:
          description: Postal code not changed
  /all:
    get:
      tags: [User]
      operationId: app.getAllUsers
      responses:
        200:
          description: Returns all users details
        500:
          description: Server error
  /delete/{user_id}:
    delete:
      tags: [User]
      operationId: app.deleteUser
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: User successfully deleted
        404:
          description: User not found
  /delete-image/{image_id}:
    delete:
      tags: [Image]
      operationId: app.deleteImage
      parameters:
        - $ref: '#/parameters/image_id'
      responses:
        200:
          description: Image successfully deleted
        404:
          description: Image not found

parameters:
  user_body:
    name: user_body
    description: Body of a user
    in: body
    schema:
      required:
        - username
        - name
        - surname
        - email
        - password
        - repeatedPassword
        - dateOfBirth
        - gender
      properties:
        username:
          type: string
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        password:
          type: string
        repeatedPassword:
          type: string
        dateOfBirth:
          type: string
        gender:
          type: string
  user_id:
    name: user_id
    description: User unique id
    in: path
    type: integer
    required: true

  image_id:
    name: image_id
    description: Image unique id
    in: path
    type: integer
    required: true

  image_body:
    name: image_body
    description: Body of a image
    in: body
    schema:
      required:
        - user_id
        - imageLink
        - isProfile
      properties:
        user_id:
          type: integer
        imageLink:
          type: string
        isProfile:
          type: boolean

  password_body:
    name: password_body
    description: Body of a password
    in: body
    schema:
      required:
        - user_id
        - newPassword
        - oldPassword
      properties:
        user_id:
          type: integer
        newPassword:
          type: string
        oldPassword:
          type: string

  phone_body:
    name: phone_body
    description: Body of a phone
    in: body
    schema:
      required:
        - user_id
        - phone
      properties:
        user_id:
          type: integer
        phone:
          type: string

  city_body:
    name: city_body
    description: Body of a city
    in: body
    schema:
      required:
        - user_id
        - city
      properties:
        user_id:
          type: integer
        city:
          type: string

  country_body:
    name: country_body
    description: Body of a country
    in: body
    schema:
      required:
        - user_id
        - country
      properties:
        user_id:
          type: integer
        country:
          type: string

  address_body:
    name: address_body
    description: Body of an address
    in: body
    schema:
      required:
        - user_id
        - address
      properties:
        user_id:
          type: integer
        address:
          type: string

  postal_body:
    name: postal_body
    description: Body of a postalCode
    in: body
    schema:
      required:
        - user_id
        - postalCode
      properties:
        user_id:
          type: integer
        postalCode:
          type: integer

  verification_body:
    name: verification_body
    description: Body of a verificaiton
    in: body
    schema:
      required:
        - user_id
        - code
      properties:
        user_id:
          type: integer
        code:
          type: string
